name: Build and test the plugin on Ubuntu

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g pnpm
      - run: pnpm install
      - run: pnpm run build
      - name: Download Ligo binary
        run: |
          wget https://gitlab.com/ligolang/ligo/-/jobs/2896100663/artifacts/raw/ligo -P $HOME
          chmod +x $HOME/ligo
      - name: Test
        run: pnpm test
        env:
          DEBUG: verdaccio*
          LIGO_BIN: $HOME/ligo
